# Source: https://openbis.readthedocs.io/en/latest/system-documentation/docker/usage.html
# Converted with: https://www.composerize.com

services:
  openbis_postgres:
    volumes:
      - type: bind
        source: ./openbis-db-data
        target: /var/lib/postgresql/data
        # noinspection ComposeUnknownKeys
        is_directory: true # This will tell Coolify to create the directory (this is not available in a normal docker-compose)
    environment:
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_OPENBISDBADMIN}
      # noinspection SpellCheckingInspection
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:${POSTGRES_IMAGE_TAG:-15}

  openbis_app:
    pid: host
    volumes:
      - type: bind
        source: ./openbis-app-data
        target: /data
          # noinspection ComposeUnknownKeys
        is_directory: true # This will tell Coolify to create the directory (this is not available in a normal docker-compose)
      - type: bind
        source: ./openbis-app-etc
        target: /etc/openbis
          # noinspection ComposeUnknownKeys
        is_directory: true
      - type: bind
        source: ./openbis-app-logs
        target: /var/log/openbis
          # noinspection ComposeUnknownKeys
        is_directory: true
    environment:
      OPENBIS_FQDN: ${SERVICE_FQDN_OPENBIS}
      OPENBIS_ADMIN_PASS: ${SERVICE_PASSWORD_OPENBISADMIN}
      OPENBIS_DATA: /data/openbis
      OPENBIS_DB_ADMIN_PASS: ${SERVICE_PASSWORD_OPENBISDBADMIN}
      OPENBIS_DB_ADMIN_USER: postgres
      OPENBIS_DB_APP_PASS: ${SERVICE_PASSWORD_OPENBISDBAPP}
      OPENBIS_DB_APP_USER: ${SERVICE_USER_OPENBISDBAPP:-openbis}
      OPENBIS_DB_HOST: openbis_postgres
      OPENBIS_ETC: /etc/openbis
      OPENBIS_HOME: /home/openbis
      OPENBIS_LOG: /var/log/openbis
    image: openbis/openbis-app:${OPENBIS_APP_IMAGE_TAG:-20.10.9}
    healthcheck:
      # https://openbis.readthedocs.io/en/latest/system-documentation/docker/verification.html
      test: |
        /home/openbis/servers/openBIS-server/jetty/bin/status.sh \
        && /home/openbis/servers/openBIS-server/jetty/bin/version.sh \
        && /home/openbis/servers/openBIS-server/jetty/bin/passwd.sh list \
        && wget -q --output-document - http://localhost:8080/openbis/webapp/eln-lims/version.txt \
        && pgrep -af DataStoreServer

  openbis_ingress:
      image: openbis/openbis-local:${OPENBIS_LOCAL_IMAGE_TAG:-latest}
      pid: host
      environment:
        SERVICE_FQDN_OPENBIS_443: /
        OPENBIS_HOST: openbis_app
