# Source: https://openbis.readthedocs.io/en/latest/system-documentation/docker/usage.html
# Converted with: https://www.composerize.com

services:
  openbis_postgres:
    volumes:
      - type: bind
        source: ./openbis-db-data
        target: /var/lib/postgresql/data
        # noinspection ComposeUnknownKeys
        is_directory: true # This will tell Coolify to create the directory (this is not available in a normal docker-compose)
    environment:
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_OPENBISDBADMIN}
      # noinspection SpellCheckingInspection
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:${POSTGRES_IMAGE_TAG:-15}

  openbis_app:
    pid: host
    volumes:
      - type: bind
        source: ./openbis-app-data
        target: /data
          # noinspection ComposeUnknownKeys
        is_directory: true # This will tell Coolify to create the directory (this is not available in a normal docker-compose)
      - type: bind
        source: ./openbis-app-etc
        target: /etc/openbis
          # noinspection ComposeUnknownKeys
        is_directory: true
      - type: bind
        source: ./openbis-app-logs
        target: /var/log/openbis
          # noinspection ComposeUnknownKeys
        is_directory: true
    environment:
      OPENBIS_FQDN: ${SERVICE_FQDN_OPENBIS}
      OPENBIS_ADMIN_PASS: ${SERVICE_PASSWORD_OPENBISADMIN}
      OPENBIS_DATA: /data/openbis
      OPENBIS_DB_ADMIN_PASS: ${SERVICE_PASSWORD_OPENBISDBADMIN}
      OPENBIS_DB_ADMIN_USER: postgres
      OPENBIS_DB_APP_PASS: ${SERVICE_PASSWORD_OPENBISDBAPP}
      OPENBIS_DB_APP_USER: ${SERVICE_USER_OPENBISDBAPP:-openbis}
      OPENBIS_DB_HOST: openbis_postgres
      OPENBIS_ETC: /etc/openbis
      OPENBIS_HOME: /home/openbis
      OPENBIS_LOG: /var/log/openbis
    image: openbis/openbis-app:${OPENBIS_APP_IMAGE_TAG:-20.10.9}
    healthcheck:
      # https://openbis.readthedocs.io/en/latest/system-documentation/docker/verification.html
      test: |
        /home/openbis/servers/openBIS-server/jetty/bin/status.sh \
        && /home/openbis/servers/openBIS-server/jetty/bin/version.sh \
        && /home/openbis/servers/openBIS-server/jetty/bin/passwd.sh list \
        && wget -q --output-document - http://localhost:8080/openbis/webapp/eln-lims/version.txt \
        && pgrep -af DataStoreServer

  openbis_ingress:
      image: haproxytech/haproxy-ubuntu:latest
      restart: always
      pid: host
      volumes:
        - type: bind
          source: ./haproxy.cfg
          target: /usr/local/etc/haproxy/haproxy.cfg
          read_only: true
          # noinspection ComposeUnknownKeys
          content: |
            global
              maxconn 1024
            
            defaults
              mode http
              option dontlognull
              option redispatch
              retries 3
              maxconn 2048
              timeout connect 10s
              timeout check   30s
              timeout client  30s
              timeout server  60s
            
            frontend openbis_ingress
              bind *:80
              acl is_as path_beg /openbis
              acl is_dss path_beg /datastore_server
              use_backend openbis_as if is_as
              use_backend openbis_dss if is_dss
              default_backend openbis_as
            
            backend openbis_as
              option forwardfor
              server as openbis-app:8080 check
            
            backend openbis_dss
              option forwardfor
              server dss openbis-app:8081 check

      environment:
        SERVICE_FQDN_OPENBIS: /
        OPENBIS_HOST: openbis_app
