version: "3.7"

services:
  openbis-db:
    container_name: openbis-db
    image: docker.io/postgres:15
    hostname: openbis-db
    environment:
      - POSTGRES_PASSWORD=aiLah4su
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - openbis-db-data:/var/lib/postgresql/data
    networks:
      - openbis-production-network

  openbis-app:
    container_name: openbis-app
    image: docker.io/openbis/openbis-app:20.10.10
    hostname: openbis-app
    depends_on:
      - openbis-db
    environment:
      - OPENBIS_ADMIN_PASS=FaH8eele
      - OPENBIS_DATA=/data/openbis
      - OPENBIS_DB_ADMIN_PASS=aiLah4su
      - OPENBIS_DB_ADMIN_USER=postgres
      - OPENBIS_DB_APP_PASS=Ay5Ing8m
      - OPENBIS_DB_APP_USER=openbis
      - OPENBIS_DB_HOST=openbis-db
      - OPENBIS_ETC=/etc/openbis
      - OPENBIS_HOME=/home/openbis
      - OPENBIS_LOG=/var/log/openbis
      - OPENBIS_FQDN=production.openbis.ch
    env_file:
      - /home/openbis/openbis-settings.env
      - /home/openbis/openbis-credentials.env
    volumes:
      - openbis-app-data:/data
      - openbis-app-etc:/etc/openbis
      - openbis-app-logs:/var/log/openbis
    ports:
      - 4180:8080
      - 4181:8081
    networks:
      - openbis-production-network


volumes:
  openbis-db-data:
    name: "openbis-db-data"
  openbis-app-data:
    name: "openbis-app-data"
  openbis-app-etc:
    name: "openbis-app-etc"
  openbis-app-logs:
    name: "openbis-app-logs"


networks:
  openbis-production-network:
    name: "openbis-production-network"

