# https://maintenant.dev/#install
services:
  maintenant:
    image: ghcr.io/kolapsis/maintenant:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - type: bind
        source: ./data
        target: /data
        # noinspection ComposeUnknownKeys
        is_directory: true
    environment:
      SERVICE_FQDN_MAINTENANT_8080: /
      MAINTENANT_ADDR: ${MAINTENANT_ADDR:-0.0.0.0:8080}
      MAINTENANT_DB: ${MAINTENANT_DB:-/data/maintenant.db}
    restart: unless-stopped
