services:
  ryot-db:
    image: postgres:16-alpine # at-least version 15 is required
    restart: unless-stopped
    container_name: ryot-db
    volumes:
      - /data/ryot/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_DB=${SERVICE_USER_POSTGRESDB:-postgres}
      - POSTGRES_USER=${SERVICE_USER_POSTGRESUSER:-postgres}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}

  ryot:
    image: ignisda/ryot:v9 # or ghcr.io/ignisda/ryot:v9
    pull_policy: always
    container_name: ryot
    restart: unless-stopped
    environment:
      _FQDN: ${SERVICE_FQDN_RYOT}
      TZ: ${TZ:-Europe/Amsterdam}
      SERVER_ADMIN_ACCESS_TOKEN: ${SERVICE_PASSWORD_RYOTADMIN}
      DATABASE_URL: "postgres://${SERVICE_USER_POSTGRESUSER:-${SERVICE_PASSWORD_POSTGRES:-password-unknown}}:postgres@postgres:5432/${SERVICE_USER_POSTGRESDB}"
      UNKEY_API_ID: ${UNKEY_KEY_ID:-}
      SERVER_PRO_KEY: ${UNKEY_KEY_SECRET:-}