services:
  hbbs:
    container_name: hbbs
    image: 'rustdesk/rustdesk-server:1.1.12'
    command: hbbs
    volumes:
      - 'ruskdesk-hbbs:/root'
    network_mode: host
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    image: 'rustdesk/rustdesk-server:1.1.12'
    command: hbbr
    volumes:
      - 'ruskdesk-hbbr:/root'
    network_mode: host
    restart: unless-stopped
