version: '3'

services:
  # docker run --rm --entrypoint /usr/bin/rustdesk-utils  sctg/sctgdesk-server-server:latest genkeypair

  hbbs:
    container_name: hbbs
    image: sctg/sctgdesk-server:latest
    command: "hbbs -r ${SERVICE_URL_RUSTDESK}:${RUSTDESK_PORT:-21117}"
    environment:
      SERVICE_FQDN_RUSTDESK: /  # for now has to be URL instead of FQDN, see https://github.com/coollabsio/coolify/issues/4104
      SERVICE_FQDN_RUSTDESK_21114:
      RUSTDESK_PORT: ${RUSTDESK_PORT:-21117}
      LOGGED_IN_ONLY: ${LOGGED_IN_ONLY:-y}
    volumes:
      - './ruskdesk-hbbs:/usr/local/share/sctgdesk'
    # network_mode OR ports + network
    # network_mode: host
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    networks:
      - sctgdesk-internal-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: sctg/sctgdesk-server:latest
    command: hbbr
    volumes:
      - './ruskdesk-hbbr:/usr/local/share/sctgdesk'
    # network_mode: host  # or ports + network
    ports:
      - ${RUSTDESK_PORT:-21117}:${RUSTDESK_PORT:-21117}
      - 21119:21119
    environment:
      PORT: ${RUSTDESK_PORT:-21117}
    networks:
      - sctgdesk-internal-net
    restart: unless-stopped


networks:
  sctgdesk-internal-net:
    external: false

